INSERT INTO "data_table_user_IQk1uY59LjYaOsyi" (land, liga, gruppe, quelle_name, quelle_url, typ, sprache, prioritaet, aktiv, hinweis, "createdAt", "updatedAt") SELECT * FROM (VALUES
('Deutschland', 'Bundesliga / 2. Bundesliga', 'offiziell', 'Bundesliga.com', 'https://www.bundesliga.com/de/', 'web', 'de', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Deutschland', '3. Liga', 'offiziell', 'DFB 3. Liga', 'https://www.dfb.de/maenner/ligen/3-liga', 'web', 'de', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('Deutschland', 'Alle Profiligen', 'medien', 'kicker', 'https://www.kicker.de/', 'web', 'de', 1, true, 'Master-Liste 01 · Nationales Fachmedium · A2', now(), now()),
('Deutschland', 'Bundesliga / 2. Bundesliga', 'medien', 'Sky Sport Deutschland – Transfer Update', 'https://sport.sky.de/fussball', 'web', 'de', 1, true, 'Master-Liste 01 · TV/Fachredaktion · A2', now(), now()),
('Deutschland', 'Alle Ligen', 'medien', 'Sportschau / ARD', 'https://www.sportschau.de/fussball/', 'web', 'de', 1, true, 'Master-Liste 01 · Öffentlich-rechtlich · A2', now(), now()),
('Deutschland', 'Alle Ligen', 'datenbank', 'Transfermarkt', 'https://www.transfermarkt.de/', 'datenbank', 'de', 1, true, 'Master-Liste 01 · Datenbank / Community · B · Nicht als alleinige Bestätigung verwenden', now(), now()),
('Deutschland', '3. Liga', 'medien', 'liga3-online.de', 'https://www.liga3-online.de/', 'web', 'de', 1, true, 'Master-Liste 01 · Spezialmedium · B', now(), now()),
('Deutschland', 'Regionalliga / Oberliga', 'medien', 'FuPa', 'https://www.fupa.net/', 'web', 'de', 1, true, 'Master-Liste 01 · Regional-/Amateurportal · B', now(), now()),
('Deutschland', 'Regionalliga West / NRW', 'medien', 'RevierSport', 'https://www.reviersport.de/', 'web', 'de', 1, true, 'Master-Liste 01 · Regionalmedium · B', now(), now()),
('Deutschland', 'Regionalliga Nordost', 'medien', 'MDR Sport', 'https://www.mdr.de/sport/fussball/index.html', 'web', 'de', 1, true, 'Master-Liste 01 · Regionaler Rundfunk · A2', now(), now()),
('Deutschland', 'Regionalliga Nord', 'medien', 'NDR Sport', 'https://www.ndr.de/sport/fussball/', 'web', 'de', 1, true, 'Master-Liste 01 · Regionaler Rundfunk · A2', now(), now()),
('Deutschland', 'Regionalliga Bayern', 'medien', 'BR24 Sport', 'https://www.br.de/nachrichten/sport/', 'web', 'de', 1, true, 'Master-Liste 01 · Regionaler Rundfunk · A2', now(), now()),
('Deutschland', 'Regionalliga Südwest', 'medien', 'SWR Sport', 'https://www.swr.de/sport/', 'web', 'de', 1, true, 'Master-Liste 01 · Regionaler Rundfunk · A2', now(), now()),
('Deutschland', 'NRW', 'medien', 'WDR Sport', 'https://www1.wdr.de/sport/fussball/index.html', 'web', 'de', 1, true, 'Master-Liste 01 · Regionaler Rundfunk · A2', now(), now()),
('Deutschland', 'Alle Ligen', 'medien', 'dpa / SID', 'https://www.dpa.com/de/', 'web', 'de', 1, true, 'Master-Liste 01 · Nachrichtenagentur · A2', now(), now()),
('Deutschland', 'Regionalliga / Amateur', 'offiziell', 'FUSSBALL.DE', 'https://www.fussball.de/', 'web', 'de', 1, true, 'Master-Liste 01 · Offizielle Verbandsplattform · A1', now(), now()),
('England', 'Premier League', 'offiziell', 'PremierLeague.com', 'https://www.premierleague.com/en', 'web', 'en', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('England', 'Championship / EFL', 'offiziell', 'EFL.com', 'https://www.efl.com/', 'web', 'en', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('England', 'Alle Profiligen', 'medien', 'BBC Sport Football', 'https://www.bbc.com/sport/football', 'web', 'en', 1, true, 'Master-Liste 01 · Nationales Qualitätsmedium · A2', now(), now()),
('England', 'Premier League / Championship', 'medien', 'Sky Sports Football', 'https://www.skysports.com/football', 'web', 'en', 1, true, 'Master-Liste 01 · TV/Fachredaktion · A2', now(), now()),
('England', 'Premier League / Championship', 'medien', 'The Athletic Football', 'https://www.nytimes.com/athletic/football/', 'web', 'en', 1, true, 'Master-Liste 01 · Premium-Fachmedium · A2', now(), now()),
('England', 'Alle Profiligen', 'medien', 'The Guardian Football', 'https://www.theguardian.com/football', 'web', 'en', 1, true, 'Master-Liste 01 · Nationales Qualitätsmedium · A2', now(), now()),
('England', 'Premier League / Championship', 'medien', 'The Telegraph Football', 'https://www.telegraph.co.uk/football/', 'web', 'en', 1, true, 'Master-Liste 01 · Nationales Qualitätsmedium · A2', now(), now()),
('England', 'Premier League / Championship', 'medien', 'The Times Football', 'https://www.thetimes.com/sport/football', 'web', 'en', 1, true, 'Master-Liste 01 · Nationales Qualitätsmedium · A2', now(), now()),
('England', 'Alle Profiligen', 'medien', 'PA Media', 'https://pa.media/', 'web', 'en', 1, true, 'Master-Liste 01 · Nachrichtenagentur · A2', now(), now()),
('England', 'Alle Ligen', 'medien', 'talkSPORT', 'https://talksport.com/football/', 'web', 'en', 3, true, 'Master-Liste 01 · Radio/Digital · B · Gerüchte stets verifizieren', now(), now()),
('England', 'Manchester Clubs', 'medien', 'Manchester Evening News', 'https://www.manchestereveningnews.co.uk/sport/football/', 'web', 'en', 1, true, 'Master-Liste 01 · Lokales Beat-Medium · A2/B', now(), now()),
('England', 'Liverpool / Everton', 'medien', 'Liverpool Echo', 'https://www.liverpoolecho.co.uk/sport/football/', 'web', 'en', 1, true, 'Master-Liste 01 · Lokales Beat-Medium · A2/B', now(), now()),
('England', 'Yorkshire / Championship', 'medien', 'Yorkshire Evening Post', 'https://www.yorkshireeveningpost.co.uk/sport/football', 'web', 'en', 1, true, 'Master-Liste 01 · Lokales Beat-Medium · A2/B', now(), now()),
('England', 'Midlands', 'medien', 'Birmingham Live Football', 'https://www.birminghammail.co.uk/sport/football/', 'web', 'en', 1, true, 'Master-Liste 01 · Lokales Beat-Medium · B', now(), now()),
('Spanien', 'LaLiga / LaLiga Hypermotion', 'offiziell', 'LaLiga.com', 'https://www.laliga.com/', 'web', 'es', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Spanien', 'Alle Profiligen', 'offiziell', 'RFEF', 'https://rfef.es/', 'web', 'es', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('Spanien', 'LaLiga', 'medien', 'Marca', 'https://www.marca.com/futbol.html', 'web', 'es', 1, true, 'Master-Liste 01 · Nationales Sportmedium · A2/B', now(), now()),
('Spanien', 'LaLiga', 'medien', 'AS', 'https://as.com/futbol/', 'web', 'es', 1, true, 'Master-Liste 01 · Nationales Sportmedium · A2/B', now(), now()),
('Spanien', 'LaLiga / Segunda', 'medien', 'Relevo', 'https://www.relevo.com/futbol/', 'web', 'es', 1, true, 'Master-Liste 01 · Digitales Fachmedium · A2', now(), now()),
('Spanien', 'Alle Profiligen', 'medien', 'Cadena SER – Carrusel/El Larguero', 'https://cadenaser.com/deportes/futbol/', 'web', 'es', 1, true, 'Master-Liste 01 · Radio/Fachredaktion · A2', now(), now()),
('Spanien', 'Alle Profiligen', 'medien', 'COPE – Deportes', 'https://www.cope.es/deportes/futbol', 'web', 'es', 1, true, 'Master-Liste 01 · Radio/Fachredaktion · A2', now(), now()),
('Spanien', 'Alle Profiligen', 'medien', 'Onda Cero – Radioestadio', 'https://www.ondacero.es/deportes/futbol/', 'web', 'es', 2, true, 'Master-Liste 01 · Radio/Fachredaktion · A2/B', now(), now()),
('Spanien', 'Barcelona / Katalonien', 'medien', 'Mundo Deportivo', 'https://www.mundodeportivo.com/futbol', 'web', 'es', 1, true, 'Master-Liste 01 · Regional/National · B', now(), now()),
('Spanien', 'Barcelona / Katalonien', 'medien', 'SPORT', 'https://www.sport.es/es/', 'web', 'es', 1, true, 'Master-Liste 01 · Regional/National · B', now(), now()),
('Spanien', 'Andalusien', 'medien', 'Estadio Deportivo', 'https://www.estadiodeportivo.com/', 'web', 'es', 1, true, 'Master-Liste 01 · Regionalmedium · B', now(), now()),
('Spanien', 'Valencia', 'medien', 'Superdeporte', 'https://www.superdeporte.es/', 'web', 'es', 1, true, 'Master-Liste 01 · Regionalmedium · B', now(), now()),
('Italien', 'Serie A', 'offiziell', 'Lega Serie A', 'https://en.legaseriea.it/', 'web', 'it', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Italien', 'Serie B', 'offiziell', 'Lega B', 'https://www.legab.it/seriebkt', 'web', 'it', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Italien', 'Alle Profiligen', 'offiziell', 'FIGC', 'https://www.figc.it/', 'web', 'it', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('Italien', 'Serie A / B', 'medien', 'Sky Sport Italia – Calciomercato', 'https://sport.sky.it/calciomercato', 'web', 'it', 1, true, 'Master-Liste 01 · TV/Fachredaktion · A2', now(), now()),
('Italien', 'Serie A / B', 'medien', 'GianlucaDiMarzio.com', 'https://gianlucadimarzio.com/', 'web', 'it', 1, true, 'Master-Liste 01 · Transfer-Spezialmedium · A2', now(), now()),
('Italien', 'Serie A / B', 'medien', 'La Gazzetta dello Sport', 'https://www.gazzetta.it/Calcio/', 'web', 'it', 1, true, 'Master-Liste 01 · Nationales Sportmedium · A2/B', now(), now()),
('Italien', 'Serie A / B', 'medien', 'Corriere dello Sport', 'https://www.corrieredellosport.it/calcio', 'web', 'it', 1, true, 'Master-Liste 01 · Nationales Sportmedium · B', now(), now()),
('Italien', 'Serie A / B', 'medien', 'Tuttosport', 'https://www.tuttosport.com/calcio', 'web', 'it', 1, true, 'Master-Liste 01 · Nationales Sportmedium · B', now(), now()),
('Italien', 'Alle Profiligen', 'medien', 'Tuttomercatoweb', 'https://www.tuttomercatoweb.com/', 'web', 'it', 1, true, 'Master-Liste 01 · Transfer-Spezialmedium · B · Einzelmeldungen verifizieren', now(), now()),
('Italien', 'Serie A / B', 'medien', 'Calciomercato.com', 'https://www.calciomercato.com/', 'web', 'it', 1, true, 'Master-Liste 01 · Transfer-Spezialmedium · B', now(), now()),
('Italien', 'Alle Profiligen', 'medien', 'ANSA Sport', 'https://www.ansa.it/sito/notizie/sport/calcio/calcio.shtml', 'web', 'it', 1, true, 'Master-Liste 01 · Nachrichtenagentur · A2', now(), now()),
('Frankreich', 'Ligue 1 / Ligue 2', 'offiziell', 'Ligue1.com / LFP', 'https://ligue1.com/', 'web', 'fr', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Frankreich', 'Alle Profiligen', 'offiziell', 'FFF', 'https://www.fff.fr/', 'web', 'fr', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('Frankreich', 'Ligue 1 / Ligue 2', 'medien', 'L''Équipe', 'https://www.lequipe.fr/Football/', 'web', 'fr', 1, true, 'Master-Liste 01 · Nationales Qualitätsmedium · A2', now(), now()),
('Frankreich', 'Ligue 1 / Ligue 2', 'medien', 'RMC Sport', 'https://rmcsport.bfmtv.com/football/', 'web', 'fr', 1, true, 'Master-Liste 01 · Radio/TV-Fachredaktion · A2', now(), now()),
('Frankreich', 'Ligue 1 / Ligue 2', 'medien', 'Foot Mercato', 'https://www.footmercato.net/', 'web', 'fr', 1, true, 'Master-Liste 01 · Transfer-Spezialmedium · B', now(), now()),
('Frankreich', 'Paris / Ligue 1', 'medien', 'Le Parisien Sport', 'https://www.leparisien.fr/sports/football/', 'web', 'fr', 1, true, 'Master-Liste 01 · Regional/National · A2/B', now(), now()),
('Frankreich', 'Westfrankreich', 'medien', 'Ouest-France Football', 'https://www.ouest-france.fr/sport/football/', 'web', 'fr', 1, true, 'Master-Liste 01 · Regionalmedium · A2/B', now(), now()),
('Frankreich', 'Nordfrankreich', 'medien', 'La Voix du Nord – Sports', 'https://www.lavoixdunord.fr/sports', 'web', 'fr', 1, true, 'Master-Liste 01 · Regionalmedium · A2/B', now(), now()),
('Frankreich', 'Südfrankreich', 'medien', 'La Provence – OM', 'https://www.laprovence.com/om', 'web', 'fr', 1, true, 'Master-Liste 01 · Regionalmedium · A2/B', now(), now()),
('Frankreich', 'Südwesten', 'medien', 'Sud Ouest Sport', 'https://www.sudouest.fr/sport/football/', 'web', 'fr', 1, true, 'Master-Liste 01 · Regionalmedium · B', now(), now()),
('Frankreich', 'Alle Regionen', 'medien', 'ici (ex-France Bleu) Sport', 'https://www.francebleu.fr/sports/football', 'web', 'fr', 1, true, 'Master-Liste 01 · Regionaler Rundfunk · A2', now(), now()),
('Niederlande', 'Eredivisie', 'offiziell', 'Eredivisie.nl', 'https://eredivisie.nl/', 'web', 'nl', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Niederlande', 'Eerste Divisie', 'offiziell', 'Keuken Kampioen Divisie', 'https://keukenkampioendivisie.nl/', 'web', 'nl', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Niederlande', 'Alle Ligen', 'offiziell', 'KNVB', 'https://www.knvb.nl/', 'web', 'nl', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('Niederlande', 'Eredivisie / KKD', 'medien', 'Voetbal International', 'https://www.vi.nl/', 'web', 'nl', 1, true, 'Master-Liste 01 · Nationales Fachmedium · A2', now(), now()),
('Niederlande', 'Alle Profiligen', 'medien', 'NOS Voetbal', 'https://nos.nl/sport/voetbal', 'web', 'nl', 1, true, 'Master-Liste 01 · Öffentlich-rechtlich · A2', now(), now()),
('Niederlande', 'Eredivisie / KKD', 'medien', 'ESPN NL Voetbal', 'https://www.espn.nl/voetbal/', 'web', 'nl', 1, true, 'Master-Liste 01 · TV/Fachredaktion · A2', now(), now()),
('Niederlande', 'Eredivisie', 'medien', 'De Telegraaf – Telesport', 'https://www.telegraaf.nl/sport/voetbal', 'web', 'nl', 1, true, 'Master-Liste 01 · Nationales Medium · A2/B', now(), now()),
('Niederlande', 'Eredivisie / KKD', 'medien', 'AD Voetbal', 'https://www.ad.nl/nederlands-voetbal/', 'web', 'nl', 1, true, 'Master-Liste 01 · National/Regional · A2/B', now(), now()),
('Niederlande', 'Alle Profiligen', 'medien', 'VoetbalPrimeur', 'https://www.voetbalprimeur.nl/', 'web', 'nl', 1, true, 'Master-Liste 01 · Digitales Fachmedium · B', now(), now()),
('Niederlande', 'Alle Profiligen', 'medien', 'FCUpdate', 'https://www.fcupdate.nl/', 'web', 'nl', 3, true, 'Master-Liste 01 · Digitales Fachmedium · B', now(), now()),
('Niederlande', 'Alle Clubs', 'medien', 'Regionale Omroepen', 'https://www.rpo.nl/', 'web', 'nl', 1, true, 'Master-Liste 01 · Regionaler Rundfunk-Verbund · A2/B · Omroep Gelderland, Rijnmond, NH, Brabant u.a. clubbezogen erfassen', now(), now()),
('Portugal', 'Liga Portugal 1 / 2', 'offiziell', 'Liga Portugal', 'https://www.ligaportugal.pt/', 'web', 'pt', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Portugal', 'Alle Ligen', 'offiziell', 'FPF', 'https://www.fpf.pt/', 'web', 'pt', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('Portugal', 'Liga Portugal', 'medien', 'A Bola', 'https://www.abola.pt/futebol', 'web', 'pt', 1, true, 'Master-Liste 01 · Nationales Sportmedium · A2/B', now(), now()),
('Portugal', 'Liga Portugal', 'medien', 'Record', 'https://www.record.pt/futebol', 'web', 'pt', 1, true, 'Master-Liste 01 · Nationales Sportmedium · A2/B', now(), now()),
('Portugal', 'Liga Portugal', 'medien', 'O Jogo', 'https://www.ojogo.pt/futebol/', 'web', 'pt', 1, true, 'Master-Liste 01 · Nationales Sportmedium · A2/B', now(), now()),
('Portugal', 'Liga Portugal', 'medien', 'Maisfutebol', 'https://maisfutebol.iol.pt/', 'web', 'pt', 1, true, 'Master-Liste 01 · Digital/TV · A2/B', now(), now()),
('Portugal', 'Alle Profiligen', 'medien', 'RTP Desporto', 'https://www.rtp.pt/noticias/desporto', 'web', 'pt', 1, true, 'Master-Liste 01 · Öffentlich-rechtlich · A2', now(), now()),
('Portugal', 'Alle Profiligen', 'medien', 'Lusa', 'https://www.lusa.pt/', 'web', 'pt', 1, true, 'Master-Liste 01 · Nachrichtenagentur · A2', now(), now()),
('Belgien', 'Jupiler Pro League / Challenger', 'offiziell', 'Pro League', 'https://www.proleague.be/', 'web', 'nl', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Belgien', 'Alle Ligen', 'offiziell', 'RBFA', 'https://www.rbfa.be/', 'web', 'nl', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('Belgien', 'Alle Profiligen', 'medien', 'Sporza Voetbal', 'https://sporza.be/nl/categorie/voetbal/', 'web', 'nl', 1, true, 'Master-Liste 01 · Öffentlich-rechtlich · A2', now(), now()),
('Belgien', 'Alle Profiligen', 'medien', 'RTBF Sport Football', 'https://www.rtbf.be/sport/football', 'web', 'fr', 1, true, 'Master-Liste 01 · Öffentlich-rechtlich · A2', now(), now()),
('Belgien', 'Pro League', 'medien', 'Het Laatste Nieuws – Voetbal', 'https://www.hln.be/voetbal/', 'web', 'nl', 1, true, 'Master-Liste 01 · Nationales Medium · A2/B', now(), now()),
('Belgien', 'Pro League', 'medien', 'Het Nieuwsblad – Voetbal', 'https://www.nieuwsblad.be/sportwereld/voetbal', 'web', 'nl', 1, true, 'Master-Liste 01 · National/Regional · A2/B', now(), now()),
('Belgien', 'Pro League', 'medien', 'La Dernière Heure / Les Sports+', 'https://www.dhnet.be/sports/football/', 'web', 'fr', 1, true, 'Master-Liste 01 · National/Regional · A2/B', now(), now()),
('Belgien', 'Alle Profiligen', 'medien', 'Walfoot', 'https://www.walfoot.be/', 'web', 'fr', 1, true, 'Master-Liste 01 · Digitales Fachmedium · B', now(), now()),
('Belgien', 'Alle Profiligen', 'medien', 'Voetbalkrant', 'https://www.voetbalkrant.com/', 'web', 'nl', 1, true, 'Master-Liste 01 · Digitales Fachmedium · B', now(), now()),
('Österreich', 'Bundesliga', 'offiziell', 'Österreichische Bundesliga', 'https://www.bundesliga.at/', 'web', 'de', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Österreich', '2. Liga', 'offiziell', '2Liga.at', 'https://www.2liga.at/', 'web', 'de', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Österreich', 'Alle Ligen', 'offiziell', 'ÖFB', 'https://www.oefb.at/', 'web', 'de', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('Österreich', 'Bundesliga / 2. Liga', 'medien', 'ORF Sport Fußball', 'https://sport.orf.at/fussball/', 'web', 'de', 1, true, 'Master-Liste 01 · Öffentlich-rechtlich · A2', now(), now()),
('Österreich', 'Bundesliga', 'medien', 'Sky Sport Austria', 'https://www.skysportaustria.at/fussball/', 'web', 'de', 1, true, 'Master-Liste 01 · TV/Fachredaktion · A2', now(), now()),
('Österreich', 'Bundesliga / 2. Liga', 'medien', 'LAOLA1', 'https://www.laola1.at/de/fussball/', 'web', 'de', 1, true, 'Master-Liste 01 · Digitales Sportmedium · A2/B', now(), now()),
('Österreich', 'Alle Ligen', 'medien', '90minuten', 'https://www.90minuten.at/de/', 'web', 'de', 1, true, 'Master-Liste 01 · Fachmedium · B', now(), now()),
('Österreich', 'Regionalligen', 'medien', 'Ligaportal', 'https://www.ligaportal.at/', 'web', 'de', 1, true, 'Master-Liste 01 · Regional-/Amateurportal · B', now(), now()),
('Schweiz', 'Super League / Challenge League', 'offiziell', 'Swiss Football League', 'https://sfl.ch/', 'web', 'de', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Schweiz', 'Alle Ligen', 'offiziell', 'SFV', 'https://www.football.ch/', 'web', 'de', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('Schweiz', 'Alle Profiligen', 'medien', 'SRF Sport Fußball', 'https://www.srf.ch/sport/fussball', 'web', 'de', 1, true, 'Master-Liste 01 · Öffentlich-rechtlich · A2', now(), now()),
('Schweiz', 'Alle Profiligen', 'medien', 'RTS Sport Football', 'https://www.rts.ch/sport/football/', 'web', 'fr', 1, true, 'Master-Liste 01 · Öffentlich-rechtlich · A2', now(), now()),
('Schweiz', 'Alle Profiligen', 'medien', 'RSI Sport Calcio', 'https://www.rsi.ch/sport/calcio/', 'web', 'it', 1, true, 'Master-Liste 01 · Öffentlich-rechtlich · A2', now(), now()),
('Schweiz', 'Super League', 'medien', 'Blick Fußball', 'https://www.blick.ch/sport/fussball/', 'web', 'de', 1, true, 'Master-Liste 01 · Nationales Medium · A2/B', now(), now()),
('Schweiz', 'Super League', 'medien', 'blue Sport', 'https://www.bluewin.ch/de/sport/fussball.html', 'web', 'de', 1, true, 'Master-Liste 01 · TV/Digital · A2/B', now(), now()),
('Schweiz', 'Alle Profiligen', 'medien', '20 Minuten Sport', 'https://www.20min.ch/sport/fussball', 'web', 'de', 3, true, 'Master-Liste 01 · Nationales Medium · B', now(), now()),
('Schweiz', 'Alle Profiligen', 'medien', 'Nau.ch Fußball', 'https://www.nau.ch/sport/fussball', 'web', 'de', 3, true, 'Master-Liste 01 · Digitales Medium · B', now(), now()),
('Türkei', 'Süper Lig / 1. Lig', 'offiziell', 'TFF und TFF Info Bank', 'https://www.tff.org/', 'web', 'tr', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('Türkei', 'Süper Lig / 1. Lig', 'medien', 'TRT Spor', 'https://www.trtspor.com.tr/futbol/', 'web', 'tr', 1, true, 'Master-Liste 01 · Öffentlich-rechtlich · A2', now(), now()),
('Türkei', 'Süper Lig', 'medien', 'beIN SPORTS Türkiye', 'https://beinsports.com.tr/futbol', 'web', 'tr', 1, true, 'Master-Liste 01 · TV/Fachredaktion · A2', now(), now()),
('Türkei', 'Süper Lig / 1. Lig', 'medien', 'Ajansspor', 'https://ajansspor.com/futbol', 'web', 'tr', 1, true, 'Master-Liste 01 · Digitales Fachmedium · A2/B', now(), now()),
('Türkei', 'Süper Lig', 'medien', 'NTV Spor', 'https://www.ntvspor.net/futbol', 'web', 'tr', 1, true, 'Master-Liste 01 · Nationales Sportmedium · A2/B', now(), now()),
('Türkei', 'Süper Lig', 'medien', 'Fanatik', 'https://www.fanatik.com.tr/futbol', 'web', 'tr', 1, true, 'Master-Liste 01 · Nationales Sportmedium · B', now(), now()),
('Türkei', 'Süper Lig', 'medien', 'Fotomaç', 'https://www.fotomac.com.tr/futbol', 'web', 'tr', 1, true, 'Master-Liste 01 · Nationales Sportmedium · B/C · Nur mit weiterer Quelle verwenden', now(), now()),
('Türkei', 'Süper Lig / 1. Lig', 'social', 'Sporx', 'https://www.sporx.com/futbol/', 'social', 'tr', 1, true, 'Master-Liste 01 · Digitales Sportmedium · B', now(), now()),
('Türkei', 'Süper Lig', 'social', 'Sports Digitale', 'https://www.youtube.com/@SportsDigitale', 'social', 'tr', 3, true, 'Master-Liste 01 · Digital/Video · B', now(), now()),
('Türkei', 'Börsennotierte Clubs', 'offiziell', 'KAP', 'https://www.kap.org.tr/', 'web', 'tr', 1, true, 'Master-Liste 01 · Unternehmens-/Börsenregister · A1 · Besonders wichtig für Galatasaray, Fenerbahçe, Beşiktaş, Trabzonspor', now(), now()),
('Schottland', 'Premiership / Championship', 'offiziell', 'SPFL', 'https://spfl.co.uk/', 'web', 'en', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Schottland', 'Alle Ligen', 'offiziell', 'Scottish FA', 'https://www.scottishfa.co.uk/', 'web', 'en', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('Schottland', 'Premiership / Championship', 'medien', 'BBC Sport Scotland Football', 'https://www.bbc.com/sport/football/scottish', 'web', 'en', 1, true, 'Master-Liste 01 · Öffentlich-rechtlich · A2', now(), now()),
('Schottland', 'Premiership', 'medien', 'Sky Sports Scottish Football', 'https://www.skysports.com/scottish-football', 'web', 'en', 1, true, 'Master-Liste 01 · TV/Fachredaktion · A2', now(), now()),
('Schottland', 'Alle Profiligen', 'medien', 'STV Sport', 'https://news.stv.tv/sport', 'web', 'en', 1, true, 'Master-Liste 01 · TV/Digital · A2', now(), now()),
('Schottland', 'Premiership / Championship', 'medien', 'Daily Record Football', 'https://www.dailyrecord.co.uk/sport/football/', 'web', 'en', 1, true, 'Master-Liste 01 · Nationales Medium · B', now(), now()),
('Schottland', 'Alle Profiligen', 'medien', 'The Scotsman Sport', 'https://www.scotsman.com/sport/football', 'web', 'en', 1, true, 'Master-Liste 01 · National/Regional · A2/B', now(), now()),
('Schottland', 'Nord/Ost', 'medien', 'Press and Journal Sport', 'https://www.pressandjournal.co.uk/category/sport/football/', 'web', 'en', 1, true, 'Master-Liste 01 · Regionalmedium · A2/B', now(), now()),
('Schottland', 'Dundee / Tayside', 'medien', 'The Courier Sport', 'https://www.thecourier.co.uk/category/sport/football/', 'web', 'en', 1, true, 'Master-Liste 01 · Regionalmedium · A2/B', now(), now()),
('Dänemark', 'Superliga', 'offiziell', 'Superliga.dk', 'https://superliga.dk/', 'web', 'da', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Dänemark', '1. Division', 'offiziell', '1-division.dk', 'https://1-division.dk/', 'web', 'da', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('Dänemark', 'Alle Ligen', 'offiziell', 'DBU', 'https://www.dbu.dk/', 'web', 'da', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('Dänemark', 'Superliga / 1. Division', 'medien', 'Tipsbladet', 'https://www.tipsbladet.dk/', 'web', 'da', 1, true, 'Master-Liste 01 · Nationales Fachmedium · A2', now(), now()),
('Dänemark', 'Alle Profiligen', 'medien', 'Bold.dk', 'https://bold.dk/', 'web', 'da', 1, true, 'Master-Liste 01 · Digitales Fachmedium · A2/B', now(), now()),
('Dänemark', 'Alle Profiligen', 'medien', 'TV 2 Sport Fodbold', 'https://sport.tv2.dk/fodbold', 'web', 'da', 1, true, 'Master-Liste 01 · TV/Fachredaktion · A2', now(), now()),
('Dänemark', 'Alle Profiligen', 'medien', 'DR Sporten Fodbold', 'https://www.dr.dk/sporten/fodbold', 'web', 'da', 1, true, 'Master-Liste 01 · Öffentlich-rechtlich · A2', now(), now()),
('Dänemark', 'Superliga', 'medien', 'Ekstra Bladet Fodbold', 'https://ekstrabladet.dk/sport/fodbold/', 'web', 'da', 1, true, 'Master-Liste 01 · Nationales Medium · B', now(), now()),
('Dänemark', 'Superliga / 1. Division', 'medien', 'B.T. Fodbold', 'https://www.bt.dk/fodbold', 'web', 'da', 1, true, 'Master-Liste 01 · Nationales Medium · B', now(), now()),
('USA', 'MLS', 'offiziell', 'MLSsoccer.com', 'https://www.mlssoccer.com/', 'web', 'en', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('USA', 'USL Championship', 'offiziell', 'USLChampionship.com', 'https://www.uslchampionship.com/', 'web', 'en', 1, true, 'Master-Liste 01 · Offizielle Liga · A1', now(), now()),
('USA', 'National', 'offiziell', 'U.S. Soccer', 'https://www.ussoccer.com/', 'web', 'en', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('USA', 'MLS', 'medien', 'The Athletic Soccer', 'https://www.nytimes.com/athletic/football/mls/', 'web', 'en', 1, true, 'Master-Liste 01 · Premium-Fachmedium · A2', now(), now()),
('USA', 'MLS', 'journalist', 'Tom Bogert', 'https://www.givemesport.com/author/tom-bogert/', 'web', 'en', 1, true, 'Master-Liste 01 · Named Insider/Reporter · A2', now(), now()),
('USA', 'MLS / USMNT', 'medien', 'ESPN Soccer', 'https://www.espn.com/soccer/', 'web', 'en', 1, true, 'Master-Liste 01 · Nationales Sportmedium · A2', now(), now()),
('USA', 'MLS / USMNT', 'medien', 'CBS Sports Golazo', 'https://www.cbssports.com/soccer/', 'web', 'en', 1, true, 'Master-Liste 01 · TV/Digital · A2/B', now(), now()),
('USA', 'MLS / USL', 'medien', 'Soccer America', 'https://www.socceramerica.com/', 'web', 'en', 1, true, 'Master-Liste 01 · Fachmedium · A2/B', now(), now()),
('USA', 'MLS / USL', 'medien', 'Backheeled', 'https://www.backheeled.com/', 'web', 'en', 3, true, 'Master-Liste 01 · Digitales Fachmedium · B', now(), now()),
('USA', 'MLS', 'offiziell', 'MLSPA Salary Guide', 'https://mlsplayers.org/resources/salary-guide', 'web', 'en', 1, true, 'Master-Liste 01 · Spielergewerkschaft · A1', now(), now()),
('USA', 'MLS', 'offiziell', 'MLS Roster Rules', 'https://www.mlssoccer.com/about/roster-rules-and-regulations', 'web', 'en', 1, true, 'Master-Liste 01 · Offizielle Liga-Dokumente · A1', now(), now()),
('China', 'CSL / China League One / Two', 'offiziell', 'Chinese Football Association', 'https://www.thecfa.cn/', 'web', 'zh', 1, true, 'Master-Liste 01 · Offizieller Verband · A1', now(), now()),
('China', 'Profiligen', 'offiziell', 'Chinese Professional Football League', 'https://www.cfl-china.cn/', 'web', 'zh', 1, true, 'Master-Liste 01 · Offizielle Ligaorganisation · A1', now(), now()),
('China', 'CSL / League One', 'medien', 'Xinhua Sports', 'https://english.news.cn/sports/', 'web', 'zh', 1, true, 'Master-Liste 01 · Staatliche Nachrichtenagentur · A2', now(), now()),
('China', 'CSL / League One', 'medien', 'Sina Sports Football', 'https://sports.sina.com.cn/china/', 'web', 'zh', 1, true, 'Master-Liste 01 · Nationales Sportportal · B', now(), now()),
('China', 'CSL / League One', 'offiziell', 'Dongqiudi (懂球帝)', 'https://www.dongqiudi.com/', 'web', 'zh', 1, true, 'Master-Liste 01 · Fußball-Spezialplattform · B · Primärquelle prüfen', now(), now()),
('China', 'CSL / League One', 'medien', 'Titan Sports (体坛周报)', 'https://www.ttplus.cn/', 'web', 'zh', 1, true, 'Master-Liste 01 · Nationales Sportmedium · A2/B', now(), now()),
('China', 'CSL / League One', 'medien', 'Soccer News / 足球报', 'https://www.zuqiubao.cn/', 'web', 'zh', 1, true, 'Master-Liste 01 · Fußball-Fachmedium · A2/B', now(), now()),
('China', 'CSL / League One', 'medien', 'Tencent Sports', 'https://sports.qq.com/', 'web', 'zh', 1, true, 'Master-Liste 01 · Nationales Digitalmedium · B', now(), now()),
('China', 'CSL / League One', 'medien', 'NetEase Sports', 'https://sports.163.com/', 'web', 'zh', 1, true, 'Master-Liste 01 · Nationales Digitalmedium · B', now(), now()),
('China', 'CSL / League One', 'medien', 'Sohu Sports', 'https://sports.sohu.com/', 'web', 'zh', 3, true, 'Master-Liste 01 · Nationales Digitalmedium · B/C · Mit Primärquellen verifizieren', now(), now()),
('China', 'CSL', 'medien', 'CCTV Sports / CCTV5', 'https://sports.cctv.com/', 'web', 'zh', 1, true, 'Master-Liste 01 · Staatlicher TV-Sender · A2', now(), now()),
('China', 'Internationale Einordnung', 'medien', 'South China Morning Post – Football', 'https://www.scmp.com/sport/football', 'web', 'en', 2, true, 'Master-Liste 01 · Internationales Qualitätsmedium · A2', now(), now()),
('Deutschland', '3. Liga', 'medien', 'kicker 3. Liga', 'https://www.kicker.de/3-liga/startseite', 'web', 'de', 1, true, 'Master-Liste 02 · Fachmedium · A2', now(), now()),
('Deutschland', '3. Liga', 'medien', 'Sportschau 3. Liga', 'https://www.sportschau.de/fussball/bundesliga3/', 'web', 'de', 1, true, 'Master-Liste 02 · Öffentlich-rechtlich · A2', now(), now()),
('Deutschland', '3. Liga', 'datenbank', 'Transfermarkt 3. Liga', 'https://www.transfermarkt.de/3-liga/startseite/wettbewerb/L3', 'datenbank', 'de', 1, true, 'Master-Liste 02 · Datenbank · B · Lizenz für kommerzielle Datennutzung klären', now(), now()),
('Deutschland', 'Regionalliga Bayern', 'offiziell', 'Bayerischer Fußball-Verband', 'https://www.bfv.de/spielbetrieb-verbandsleben/regionalliga-bayern', 'web', 'de', 1, true, 'Master-Liste 02 · Offizieller Verband · A1', now(), now()),
('Deutschland', 'Regionalliga Nord', 'offiziell', 'Norddeutscher Fußball-Verband', 'https://www.nordfv.de/spielbetrieb/regionalliga-herren', 'web', 'de', 1, true, 'Master-Liste 02 · Offizieller Verband · A1', now(), now()),
('Deutschland', 'Regionalliga Nordost', 'offiziell', 'NOFV', 'https://www.nofv-online.de/', 'web', 'de', 1, true, 'Master-Liste 02 · Offizieller Verband · A1', now(), now()),
('Deutschland', 'Regionalliga West', 'offiziell', 'WDFV', 'https://wdfv.de/spielbetrieb/regionalliga-west.html', 'web', 'de', 1, true, 'Master-Liste 02 · Offizieller Verband · A1', now(), now()),
('Deutschland', 'Regionalliga Südwest', 'offiziell', 'Regionalliga Südwest', 'https://www.regionalliga-suedwest.de/', 'web', 'de', 1, true, 'Master-Liste 02 · Offizielle Liga · A1', now(), now()),
('Deutschland', 'Regionalliga', 'medien', 'FuPa Regionalliga', 'https://www.fupa.net/league/regionalliga', 'web', 'de', 1, true, 'Master-Liste 02 · Regionalportal · B', now(), now()),
('Deutschland', 'Regionalliga', 'datenbank', 'Transfermarkt Regionalliga', 'https://www.transfermarkt.de/wettbewerbe/national/wettbewerbe/40', 'datenbank', 'de', 1, true, 'Master-Liste 02 · Datenbank · B · Kommerzielle Nutzung lizenzieren', now(), now()),
('Deutschland', 'Regionalliga West', 'medien', 'RevierSport', 'https://www.reviersport.de/fussball/regionalligawest.html', 'web', 'de', 1, true, 'Master-Liste 02 · Regionalmedium · B', now(), now()),
('Deutschland', 'Regionalliga Nordost', 'medien', 'rbb24 Sport', 'https://www.rbb24.de/sport/', 'web', 'de', 1, true, 'Master-Liste 02 · Regionaler Rundfunk · A2', now(), now()),
('Deutschland', 'Regionalliga Südwest', 'medien', 'SR Sport', 'https://www.sr.de/sr/home/sport/index.html', 'web', 'de', 1, true, 'Master-Liste 02 · Regionaler Rundfunk · A2', now(), now()),
('Deutschland', 'Regionalliga/Oberliga', 'medien', '4-liga.com', 'https://www.4-liga.com/', 'web', 'de', 3, true, 'Master-Liste 02 · Spezialmedium · B/C · Meldungen verifizieren', now(), now())
) AS v(land, liga, gruppe, quelle_name, quelle_url, typ, sprache, prioritaet, aktiv, hinweis, "createdAt", "updatedAt") WHERE NOT EXISTS (SELECT 1 FROM "data_table_user_IQk1uY59LjYaOsyi" q WHERE regexp_replace(lower(q.quelle_url), '^https?://(www\.)?', '') = regexp_replace(lower(v.quelle_url), '^https?://(www\.)?', '') OR rtrim(regexp_replace(lower(q.quelle_url), '^https?://(www\.)?', ''), '/') = rtrim(regexp_replace(lower(v.quelle_url), '^https?://(www\.)?', ''), '/'));